### PR TITLE
Add reStructuredText to scopes enabled by default

### PR DESCRIPTION
**Pull request by mettekou**

### CODE REVIEW

**Comment by Arcanemagus** [comment]
Is there a reason this needs to be added to the _default_? The entire point of making the scopes configurable was so that languages like that could be easily added if a user choses.

**Comment by mettekou** [comment]
> Is there a reason this needs to be added to the default? The entire point of making the scopes configurable was so that languages like that could be easily added if a user choses.

This is a non-breaking change that does not get in the way of users of other formats, but saves users of reStructuredText the time of having to look up the exact name of the scope. Because LaTeX, Markdown, and AsciiDoc are already available by default, why not provide a seamless experience for users of reStructuredText as well?

**Comment by Arcanemagus** [comment]
Merging, I don't really want that list to balloon out of control, but I guess if you've cared enough to submit a PR then there are probably enough others using that language to warrant its addition. 😉

**Comment by Arcanemagus** [comment]
Just noticed a release hadn't been published including this, v3.2.0 is out now!

**Pull request merged**
